### ISSUE TITLE
user_config.json is not found but its in the right place

### ISSUE THREAD

**Issue by legochad** [zefie/zefie_wtvp_minisrv#18]
![image](https://user-images.githubusercontent.com/113802722/213036141-ac1e8a2f-1324-43fd-8dea-cc0237f5a546.png)

![image](https://user-images.githubusercontent.com/113802722/213036240-1e433a4d-cf2c-4763-b8e6-631f49bbb33a.png)

**Comment by zefie** [comment]
This can happen when the syntax of the json file is invalid. Please verify your user_config.json with a jslint checker. Your screenshot seems to indicate an unexpected `:`

**Comment by legochad** [comment]
i used the example of the user_config

**Comment by legochad** [comment]
i fixed it i just used the example again and it works
