### ISSUE TITLE
Menu panel broken

### ISSUE THREAD

**Issue by Tailsthecutefox** [zefie/zefie_wtvp_minisrv#21]
when pressing the key to open the menu for example "del" on the viewer instead of opening the menu it just makes the same sound as trying to go down at the bottom and bgm also wont load, only when i open tv home and open a page in there does the menu open again and the bgm load

on a seperate note user_config.json needs to exist or it wont load and all the files in includes/servicevault need to be in userservicevault or they wont be found

**Comment by Tailsthecutefox** [comment]
ah ok thanks for the clarification thought it was related to the server not liking me adding new services like wtv-center

**Comment by zefie** [comment]
> on a seperate note user_config.json needs to exist or it wont load and all the files in includes/servicevault need to be in userservicevault or they wont be found

I was able to reproduce this once in a linux environment, but not again on my Windows development environment. This may be related to a specific node version. I will look into this more.

**Comment by Tailsthecutefox** [comment]
> > on a seperate note user_config.json needs to exist or it wont load and all the files in includes/servicevault need to be in userservicevault or they wont be found
> 
> I was able to reproduce this once in a linux environment, but not again on my Windows development environment. This may be related to a specific node version. I will look into this more.

Yeah i got this error on windows with my currently installed node.js version which was the latest when i got the issue
but yeah the version is v20.10.0 for windows on windows 10 with npm version 10.2.3 and with the following modules enabled

  npm: '10.2.3',
  node: '20.10.0',
  acorn: '8.10.0',
  ada: '2.7.2',
  ares: '1.20.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.57.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdutf: '3.2.18',
  tz: '2023c',
  undici: '5.26.4',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.25',
  zlib: '1.2.13.1-motley'

**Comment by zefie** [comment]
The user_config.json issue should be fixed with 1e642ffe85fe9e7aae3311f05be482aa0913ae87, if not feel free to reopen this issue
