### ISSUE TITLE
Spelling mistakes on noscroll and nooptions

### ISSUE THREAD

**Issue by TheMsntv2Guy** [zefie/zefie_wtvp_minisrv#26]
![image](https://github.com/zefie/zefie_wtvp_minisrv/assets/149720149/e04d507b-3d55-4505-9c5b-f5792d6f2747)

**Comment by TheMsntv2Guy** [comment]
This is one includes/servicevault/wtv-star/star

**Comment by zefie** [comment]
Fixed in d77a727fb8caa46c0176cc0fdb6fd4a8f0f08676
