### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by acrinym** [zefie/zefie_wtvp_minisrv#4]
So a feature on the HTML-Editor page: 
Audioscope generator. 

I remember seeing one when I was on WebTV Years ago, I bet I could find one again to add. :)

The other thing I bet that could be done is to take the Wtv-BG-music code and make a standalone music player. 

One more thing....is it possible to make the wtv-viewer continue playing music even after the window is not selected? That could possibly be "rectified" by forcing the window to think it's still active.

**Comment by zefie** [comment]
> So a feature on the HTML-Editor page: Audioscope generator.
> 
> I remember seeing one when I was on WebTV Years ago, I bet I could find one again to add. :)

There have been discussions about adding a small audioscope generator and a few user save slots to store them. Maybe after mail and discuss is implemented so users have a place to show them off :)

> The other thing I bet that could be done is to take the Wtv-BG-music code and make a standalone music player.
Not sure what you mean here.

> One more thing....is it possible to make the wtv-viewer continue playing music even after the window is not selected? That could possibly be "rectified" by forcing the window to think it's still active.

I wish. I took a look at it in IDA but do not know assembly well enough to find the routine that is doing that and `nop` it or whatever.

**Comment by SKCro** [comment]
> One more thing....is it possible to make the wtv-viewer continue playing music even after the window is not selected? That could possibly be "rectified" by forcing the window to think it's still active.

@zefie I noticed the old 1.0 (red smiley face) version continues to play in the background, while newer ones like 2.0 and 4.1 don't. Maybe look at the differences between 1.0 and 2.0 or something and try to figure it out from there?

**Comment by zefie** [comment]
> > One more thing....is it possible to make the wtv-viewer continue playing music even after the window is not selected? That could possibly be "rectified" by forcing the window to think it's still active.
> 
> @zefie I noticed the old 1.0 (red smiley face) version continues to play in the background, while newer ones like 2.0 and 4.1 don't. Maybe look at the differences between 1.0 and 2.0 or something and try to figure it out from there?

@Sgeo implemented this, included in the viewergen in 040e035548b08890e088bf8d1d4785e4e86dfd23.
