### ISSUE TITLE
Use Production HTTP response messages

### ISSUE THREAD

**Issue by JarHead4** [zefie/zefie_wtvp_minisrv#5]
As of right now, the server just responds with generic messages like "Not Found" or "Bad Gateway", while they should be more user friendly, as shown below:
"Not Found" --> "The publisher can't find the page requested."
"Access Denied" --> "The publisher of that page has not authorized you to use it."
(Currently non-existant) "Unknown Host" --> "The publisher (URL w/o http://) is unknown"

Any other ones I missed should be present in ROM, file US017.dat

**Comment by zefie** [comment]
Should be addressed in b20d09d
